using Content.Client.UserInterface.Controls;
using Content.Shared._VXS14.WeaponMonitoring;
using Content.Shared._VXS14.WeaponMonitoring.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._VXS14.WeaponMonitoring;

[GenerateTypedNameReferences]
public sealed partial class WeaponMonitoringConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private readonly EntityUid _console;
    private List<WeaponMonitoringConsoleEntry> _entries = new();
    private int? _selectedIndex;

    public Action? OnRefreshRequested;
    public Action<WeaponMonitoringControlAction, NetEntity>? OnControlActionRequested;

    public WeaponMonitoringConsoleWindow(EntityUid console)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _console = console;

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        WeaponsList.OnItemSelected += args =>
        {
            _selectedIndex = args.ItemIndex;
            UpdateSelected(args.ItemIndex);
        };
        SetBombTargetButton.OnPressed += _ => TrySendAction(WeaponMonitoringControlAction.SetBombTarget);
        ControlGunButton.OnPressed += _ => TrySendAction(WeaponMonitoringControlAction.ControlGun);
        LaunchRocketButton.OnPressed += _ => TrySendAction(WeaponMonitoringControlAction.LaunchRocket);

        SetStationName();
        ClearSelection();
    }

    public void UpdateState(WeaponMonitoringConsoleState state)
    {
        var previousEntity = GetSelectedEntity();

        _entries = state.Entries;
        WeaponsList.Clear();

        for (var index = 0; index < _entries.Count; index++)
        {
            var entry = _entries[index];
            var category = Loc.GetString(GetCategoryLocKey(entry.Category));
            WeaponsList.AddItem($"[{category}] {entry.Name}");
        }

        if (_entries.Count == 0)
        {
            _selectedIndex = null;
            ClearSelection();
            return;
        }

        var selectedIndex = previousEntity == null
            ? 0
            : _entries.FindIndex(x => x.Entity == previousEntity.Value);

        if (selectedIndex < 0)
            selectedIndex = 0;

        WeaponsList.ClearSelected();
        WeaponsList[selectedIndex].Selected = true;
        _selectedIndex = selectedIndex;
        UpdateSelected(selectedIndex);
    }

    private void SetStationName()
    {
        var stationName = Loc.GetString("power-monitoring-window-unknown-location");

        if (_entManager.TryGetComponent(_console, out TransformComponent? xform) &&
            xform.GridUid != null &&
            _entManager.TryGetComponent(xform.GridUid, out MetaDataComponent? stationMetaData))
        {
            stationName = stationMetaData.EntityName;
        }

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("weapon-monitoring-window-station-name", ("stationName", stationName)));
        StationName.SetMessage(msg);
    }

    private NetEntity? GetSelectedEntity()
    {
        if (_selectedIndex == null || _selectedIndex < 0 || _selectedIndex >= _entries.Count)
            return null;

        return _entries[_selectedIndex.Value].Entity;
    }

    private void UpdateSelected(int index)
    {
        if (index < 0 || index >= _entries.Count)
        {
            ClearSelection();
            return;
        }

        _selectedIndex = index;

        var entry = _entries[index];
        SelectedWeaponName.Text = entry.Name;
        CategoryValue.Text = Loc.GetString(GetCategoryLocKey(entry.Category));
        FovValue.Text = FormatValue(entry.Fov, "weapon-monitoring-window-fov-value");
        SeekerValue.Text = string.IsNullOrWhiteSpace(entry.SeekerType)
            ? Loc.GetString("weapon-monitoring-window-value-unknown")
            : entry.SeekerType;
        WarheadValue.Text = string.IsNullOrWhiteSpace(entry.WarheadType)
            ? Loc.GetString("weapon-monitoring-window-value-unknown")
            : entry.WarheadType;
        FlightTimeValue.Text = FormatValue(entry.FlightTime, "weapon-monitoring-window-flight-time-value");
        DeviationValue.Text = FormatValue(entry.Deviation, "weapon-monitoring-window-deviation-value");
        ProjectileSpeedValue.Text = FormatValue(entry.ProjectileSpeed, "weapon-monitoring-window-speed-value");

        var notes = string.IsNullOrWhiteSpace(entry.Notes)
            ? Loc.GetString("weapon-monitoring-window-notes-empty")
            : entry.Notes;

        NotesValue.SetMessage(notes);

        SetBombTargetButton.Disabled = entry.Category != WeaponMonitoringCategory.AerialBomb;
        ControlGunButton.Disabled = entry.Category != WeaponMonitoringCategory.NavalGun;
        LaunchRocketButton.Disabled = entry.Category != WeaponMonitoringCategory.AntiShipMissile;
    }

    private void ClearSelection()
    {
        _selectedIndex = null;
        SelectedWeaponName.Text = Loc.GetString("weapon-monitoring-window-no-selection");
        CategoryValue.Text = "-";
        FovValue.Text = "-";
        SeekerValue.Text = "-";
        WarheadValue.Text = "-";
        FlightTimeValue.Text = "-";
        DeviationValue.Text = "-";
        ProjectileSpeedValue.Text = "-";
        NotesValue.SetMessage(Loc.GetString("weapon-monitoring-window-notes-empty"));
        SetBombTargetButton.Disabled = true;
        ControlGunButton.Disabled = true;
        LaunchRocketButton.Disabled = true;
    }

    private void TrySendAction(WeaponMonitoringControlAction action)
    {
        var selected = GetSelectedEntity();
        if (selected == null)
            return;

        OnControlActionRequested?.Invoke(action, selected.Value);
    }

    private string FormatValue(float? value, string formatLocKey)
    {
        if (value == null)
            return Loc.GetString("weapon-monitoring-window-value-unknown");

        return Loc.GetString(formatLocKey, ("value", value.Value));
    }

    private string GetCategoryLocKey(WeaponMonitoringCategory category)
    {
        return category switch
        {
            WeaponMonitoringCategory.AntiShipMissile => "weapon-monitoring-window-category-missile",
            WeaponMonitoringCategory.AerialBomb => "weapon-monitoring-window-category-bomb",
            WeaponMonitoringCategory.NavalGun => "weapon-monitoring-window-category-gun",
            _ => "weapon-monitoring-window-value-unknown"
        };
    }
}
