- type: roleLoadout
  id: JobSolfedRifleman
  groups:
  - GlassesSolfedStandartissue
  - ShoesCombatStandartissue
  - GlovesCombatStandartissue
  - ArmorPlatesStandartissue
  - ArmorPlatecarriersStandartissue
  - MasksStandartissue
  - HatsStandartissue
