- type: entity
  id: SpawnPointDebugRole
  parent: SpawnPointJobBase
  name: debug role spawner
  components:
  - type: SpawnPoint
    job_id: DebugRole
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointDebugRole2
  parent: SpawnPointJobBase
  name: debug role 2 spawner
  components:
  - type: SpawnPoint
    job_id: DebugRole2
  - type: Sprite
    layers:
      - state: green
      - state: passenger
