- type: entity
  id: SpawnPointSolfed
  parent: SpawnPointJobBase
  name: debug role spawner
  components:
  - type: SpawnPoint
    spawn_type: LateJoin
    round_start: true
    job_id: Solfed
  - type: Sprite
    layers:
      - state: green
      - state: passenger

- type: entity
  id: SpawnPointSyndy
  parent: SpawnPointJobBase
  name: debug role 2 spawner
  components:
  - type: SpawnPoint
    spawn_type: LateJoin
    round_start: true
    job_id: Syndy
  - type: Sprite
    layers:
      - state: green
      - state: passenger
