- type: loadoutGroup
  id: BeltsSolfedRifleman
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingLecter
  - ClothingBeltMilitaryWebbingLecterCrowbarLoadout
  - ClothingBeltMilitaryWebbingLecterGrenadesLoadout

- type: loadoutGroup
  id: BeltsSolfedSeniorRifleman
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingLecter
  - ClothingBeltMilitaryWebbingLecterCrowbarLoadout
  - ClothingBeltMilitaryWebbingLecterGrenadesLoadout
  - ClothingBeltMilitaryWebbingRPKLoadout
  - ClothingBeltMilitaryWebbingExhaustLoadout

- type: loadoutGroup
  id: BeltsSolfedEngineer
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingLecter
  - ClothingBeltMilitaryWebbingLecterCrowbarLoadout
  - ClothingBeltMilitaryWebbingEngineeringLecterLoadout
  - ClothingBeltMilitaryWebbingEngineeringWTLoadout
  - ClothingBeltMilitaryWebbingWTLoadout

- type: loadoutGroup
  id: BeltsSolfedCorpsman
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingLecter
  - ClothingBeltMilitaryWebbingLecterCrowbarLoadout
  - ClothingBeltMilitaryWebbingWTLoadout

- type: loadoutGroup
  id: BeltsSyndy
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingVereskLoadout
  - ClothingBeltMilitaryWebbingC20rLoadout
  - ClothingBeltMilitaryWebbingM90Loadout
  - ClothingBeltMilitaryWebbingBulldogLoadout
  - ClothingBeltMilitaryWebbingL6Loadout
  - ClothingBeltMilitaryWebbingLecterGrenadesLoadout

- type: loadoutGroup
  id: BeltsSyndyCommander
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingM90Loadout
  - ClothingBeltMilitaryWebbingVereskLoadout
  - ClothingBeltMilitaryWebbingC20rLoadout

- type: loadoutGroup
  id: BeltsSyndyOperative
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingM90Loadout
  - ClothingBeltMilitaryWebbingVereskLoadout
  - ClothingBeltMilitaryWebbingC20rLoadout

- type: loadoutGroup
  id: BeltsSyndyMarksman
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingSvyatLoadout
  - ClothingBeltMilitaryWebbingHristovLoadout
  - ClothingBeltMilitaryWebbingVereskLoadout

- type: loadoutGroup
  id: BeltsSyndyAssaulter
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingM90Loadout
  - ClothingBeltMilitaryWebbingVereskLoadout
  - ClothingBeltMilitaryWebbingC20rLoadout
  - ClothingBeltMilitaryWebbingBulldogLoadout
  - ClothingBeltMilitaryWebbingL6Loadout

- type: loadoutGroup
  id: BeltsSyndyMedic
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingM90Loadout
  - ClothingBeltMilitaryWebbingVereskLoadout
  - ClothingBeltMilitaryWebbingC20rLoadout

- type: loadoutGroup
  id: BeltsSyndyPilot
  name: loadout-group-vxs-belts
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingBeltMilitaryWebbingVereskLoadout
  - ClothingBeltMilitaryWebbingC20rLoadout
