- type: loadoutGroup
  id: GlovesCombatStandartissue
  name: loadout-group-vxs-gloves
  minLimit: 0
  maxLimit: 1
  loadouts:
  - GlovesCombatStandartissue
  - GlovesCombatInsuls
  - GlovesBlackStandart
  - GlovesBlackStandartFingerless
  - GlovesCombatMercenaryFingerless
  - GlovesCombatMercenaryCombat

- type: loadoutGroup
  id: GlovesSyndicateStandartissue
  name: loadout-group-vxs-gloves
  minLimit: 0
  maxLimit: 1
  loadouts:
  - GlovesCombatStandartissue
  - GlovesBlackStandart
  - GlovesBlackStandartFingerless
  - GlovesCombatMercenaryFingerless
  - GlovesCombatMercenaryCombat
