- type: loadoutGroup
  id: UniformsSyndicate
  name: loadout-group-security-jumpsuit
  minLimit: 0
  maxLimit: 1
  loadouts:
  - UniformCasualBlueLoadout
  - UniformCasualRedLoadout
  - UniformCasualGreenLoadout
  - UniformCasualPurpleLoadout
  - UniformLawyerBlackLoadout
  - UniformOperativeLoadout
  - UniformHawaiBlackLoadout
  - UniformHawaiBlueLoadout
  - UniformHawaiRedLoadout
  - UniformHawaiYellowLoadout
