using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.ArtilleryDetection;
using Content.Client.UserInterface.Controls;
using System;

namespace Content.Client.ArtilleryDetection;

[GenerateTypedNameReferences]
public sealed partial class ArtilleryDetectionConsoleWindow : FancyWindow
{
    public readonly EntityUid Console;

    public Action<Guid>? OnDeleteEvent;
    public Action? OnRefreshRequested;

    private ArtilleryDetectionConsoleState? _currentState;
    private Guid? _selectedEventId;

    public ArtilleryDetectionConsoleWindow(EntityUid console)
    {
        RobustXamlLoader.Load(this);
        Console = console;
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        DeleteButton.OnPressed += _ =>
        {
            if (_selectedEventId.HasValue)
                OnDeleteEvent?.Invoke(_selectedEventId.Value);
        };
        ClearAllButton.OnPressed += _ =>
        {
            if (_currentState != null)
            {
                foreach (var evt in _currentState.Events)
                {
                    OnDeleteEvent?.Invoke(evt.Id);
                }
            }
        };

        EventList.OnItemSelected += args =>
        {
            if (args.ItemIndex >= 0 && args.ItemIndex < _currentState?.Events.Count)
            {
                _selectedEventId = _currentState.Events[args.ItemIndex].Id;
            }
        };

        OnClose += () => Close();
    }

    public void UpdateState(ArtilleryDetectionConsoleState state)
    {
        _currentState = state;
        EventList.Clear();

        if (state.Events.Count == 0)
        {
            StatusLabel.Text = "No events detected.";
            return;
        }

        for (int i = 0; i < state.Events.Count; i++)
        {
            var evt = state.Events[i];
            var text = $"[{evt.DetectionTime:mm\\:ss}] {evt.WeaponType} - Coordinates: ({evt.DetectedCoordinates.X:F1}, {evt.DetectedCoordinates.Y:F1})";
            EventList.AddItem(text);
        }

        StatusLabel.Text = $"{state.Events.Count} events detected.";
    }
}
