- type: loadout
  id: OuterVestWebLoadout
  equipment:
    outerClothing: ClothingOuterVestWeb

- type: loadout
  id: OuterArmorPlateCarrierLoadout
  equipment:
    outerClothing: ClothingOuterArmorPlateCarrier
